apiVersion: apps/v1
kind: Deployment
metadata:
  name: apica-react-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: apica-react-app
  template:
    metadata:
      labels:
        app: apica-react-app
    spec:
      containers:
      - name: apica-react-app
        image: apica-react-app-image:latest
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: apica-react-app-service
spec:
  selector:
    app: apica-react-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: LoadBalancer

